<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="VideoLibrary" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\..\CanvasManagement.Interfaces\CanvasManagement.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icons\vlc.svg" />
  </ItemGroup>

</Project>
